from typing import Any

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """
    Task:
        Pydantic model representing a user chat query payload, optionally including session identifiers and PDF configurations.

    Input_Params:
        message (str):
            The user prompt or query text.
            Example: "Show all transactions above 5000"
        session_id (str | None):
            Optional session identifier to maintain conversation history.
            Example: "session-12345"
        pdf_path (str | None):
            Optional local file path to a PDF document to analyze.
            Example: "uploads/invoice.pdf"
        use_ocr (bool):
            Whether to use OCR for PDF extraction.
            Example: False

    Output_Params:
        None

    Returns:
        None
    """
    message: str = Field(..., min_length=1)
    session_id: str | None = None
    pdf_path: str | None = Field(
        default=None,
        description="Path to a PDF under uploads/ or project root",
    )
    use_ocr: bool = False


class ChatResponse(BaseModel):
    """
    Task:
        Pydantic model representing the response schema for a chat query, summarizing the agent's answer and execution traces.

    Input_Params:
        answer (str):
            The textual response generated by the agent.
            Example: "Here is the list of high-value transactions..."
        session_id (str):
            The session identifier associated with the request.
            Example: "session-12345"
        sql_used (str | None):
            Optional SQL query generated and executed by the database agent.
            Example: "SELECT * FROM transactions WHERE amount > 5000;"
        rows_preview (list[dict[str, Any]] | None):
            Optional list of database rows retrieved by the executed SQL.
            Example: [{"id": 1, "amount": 6000}]
        intent (str | None):
            Optional classified intent of the user's message.
            Example: "sql_query"
        pdf_preview (str | None):
            Optional snippet of extracted text or preview from the processed PDF.
            Example: "Invoice total: $1,200..."
        pdf_file (str | None):
            Optional path or reference to the processed PDF file.
            Example: "uploads/invoice.pdf"

    Output_Params:
        None

    Returns:
        None
    """
    answer: str
    session_id: str
    sql_used: str | None = None
    rows_preview: list[dict[str, Any]] | None = None
    intent: str | None = None
    pdf_preview: str | None = None
    pdf_file: str | None = None


class PdfExtractResponse(BaseModel):
    """
    Task:
        Pydantic model representing the response schema for a single PDF text extraction request.

    Input_Params:
        success (bool):
            Indicates whether the PDF text extraction succeeded.
            Example: True
        file (str):
            The path to the extracted PDF file.
            Example: "uploads/invoice.pdf"
        char_count (int):
            The total number of characters extracted from the PDF.
            Example: 4500
        truncated (bool):
            Indicates whether the extracted text was truncated to fit context limits.
            Example: False
        use_ocr (bool):
            Indicates whether OCR was utilized during the extraction process.
            Example: False
        text (str | None):
            Optional extracted raw text content of the PDF.
            Example: "Reliance Industries Limited Invoice..."
        summary (str | None):
            Optional text summary of the PDF content generated by the agent.
            Example: "This document is a purchase order for..."
        error (str | None):
            Optional error message if the extraction failed.
            Example: "File not found"

    Output_Params:
        None

    Returns:
        None
    """
    success: bool
    file: str
    char_count: int
    truncated: bool
    use_ocr: bool
    text: str | None = None
    summary: str | None = None
    error: str | None = None


class PdfBatchRequest(BaseModel):
    """
    Task:
        Pydantic model representing the request payload for batch PDF text extraction from a directory.

    Input_Params:
        directory (str):
            Directory path containing PDF files to process.
            Example: "uploads/batch1"
        use_ocr (bool):
            Whether to use OCR for processing PDF files in the batch.
            Example: False
        output_directory (str | None):
            Optional directory path where extracted texts/summaries should be saved.
            Example: "outputs/batch1"

    Output_Params:
        None

    Returns:
        None
    """
    directory: str = Field(..., description="Directory path containing PDF files")
    use_ocr: bool = False
    output_directory: str | None = None


class PdfBatchResponse(BaseModel):
    """
    Task:
        Pydantic model representing the response payload for a batch PDF processing request.

    Input_Params:
        directory (str):
            The processed directory path.
            Example: "uploads/batch1"
        file_count (int):
            The total number of PDF files discovered and processed.
            Example: 5
        results (dict[str, Any]):
            Dictionary mapping each file name to its processing metadata or extraction status.
            Example: {"doc1.pdf": {"success": True, "chars": 1200}}

    Output_Params:
        None

    Returns:
        None
    """
    directory: str
    file_count: int
    results: dict[str, Any]


class QuoteItem(BaseModel):
    """
    Task:
        Pydantic model representing a single product line item inside a sales quote request.

    Input_Params:
        product_id (str):
            The unique identifier of the product.
            Example: "PROD-101"
        quantity (float):
            The ordered or quoted quantity of the product.
            Example: 15.0
        price (float):
            The unit price of the product.
            Example: 99.99

    Output_Params:
        None

    Returns:
        None
    """
    product_id: str
    quantity: float
    price: float


class QuoteRequest(BaseModel):
    """
    Task:
        Pydantic model representing the input payload for generating a customer sales quote document.

    Input_Params:
        customer_no (str):
            The customer reference number.
            Example: "CUST-998"
        items (list[QuoteItem]):
            The list of products, quantities, and prices to include in the quote.
            Example: [{"product_id": "PROD-101", "quantity": 10.0, "price": 5.0}]

    Output_Params:
        None

    Returns:
        None
    """
    customer_no: str = Field(..., min_length=1)
    items: list[QuoteItem] = Field(..., min_length=1)


class QuoteResponse(BaseModel):
    """
    Task:
        Pydantic model representing the response schema returned after generating a sales quote.

    Input_Params:
        success (bool):
            Indicates whether the sales quote generation succeeded.
            Example: True
        file_created (str | None):
            Optional file path to the generated quote PDF document.
            Example: "outputs/quotes/CUST-998_quote.pdf"
        message (str | None):
            Optional informational message or status details.
            Example: "Quote PDF generated successfully."
        quote (dict[str, Any] | None):
            Optional dictionary summarizing the final constructed quote metadata and pricing calculations.
            Example: {"grand_total": 50.0, "items_count": 1}
        error (str | None):
            Optional error message if quote generation failed.
            Example: "Invalid customer ID"

    Output_Params:
        None

    Returns:
        None
    """
    success: bool
    file_created: str | None = None
    message: str | None = None
    quote: dict[str, Any] | None = None
    error: str | None = None


class HealthResponse(BaseModel):
    """
    Task:
        Pydantic model representing the health status response of the application.

    Input_Params:
        status (str):
            The status string of the health check.
            Example: "ok"

    Output_Params:
        None

    Returns:
        None
    """
    status: str


class ReadyResponse(BaseModel):
    """
    Task:
        Pydantic model representing detailed system readiness status, including database connectivity and schema caching.

    Input_Params:
        status (str):
            The overall readiness status string.
            Example: "ready"
        database (bool):
            Indicates whether database connectivity is active and working.
            Example: True
        schema_cached (bool):
            Indicates whether the database schema catalogs have been successfully cached.
            Example: True

    Output_Params:
        None

    Returns:
        None
    """
    status: str
    database: bool
    schema_cached: bool
